# This is a GitHub Actions workflow file.
# It defines a set of automated steps that will run when you push code.
# In this case, it deploys your website files to a server via SFTP.

name: 🚀 Deploy Website via SFTP

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code so the workflow can access it
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Step 2: Sync files to the hosting server using a new, more robust SFTP action
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # These are the secrets you created in your GitHub repository settings
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        
        # This is the destination path on your remote server
        # I've updated this to point to your test directory.
        server-dir: domains/skylinecommerce.in/public_html/test/