# This is a GitHub Actions workflow file.
# It defines a set of automated steps that will run when you push code.
# In this case, it deploys your website files to a server via SFTP.

name: 🚀 Deploy Website via SFTP

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code so the workflow can access it
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Step 2: Sync files to the hosting server using a dedicated SFTP action
    - name: 📂 Sync files
      uses: easingthemes/sftp-deploy@v4.0.1
      with:
        # These are the secrets you created in your GitHub repository settings
        sftp_host: ${{ secrets.SFTP_SERVER }}
        sftp_port: ${{ secrets.SFTP_PORT }}
        sftp_username: ${{ secrets.SFTP_USERNAME }}
        sftp_password: ${{ secrets.SFTP_PASSWORD }}
        
        # This is the destination path on your remote server.
        # The './' is important for this action.
        remote_path: ./domains/skylinecommerce.in/test/