# This is a GitHub Actions workflow file.
# It defines a set of automated steps that will run when you push code.
# This version uses rsync over SSH for a more robust and professional deployment.

name: 🚀 Deploy Website via Rsync/SSH

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code so the workflow can access it
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Step 2: Install the SSH private key from your repository secrets
    - name: 🔑 Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        # This is the private key you will add to your repository secrets
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # The known_hosts is required by the action, but we will disable strict checking
        known_hosts: 'placeholder'

    # Step 3: Deploy files to the server using rsync for a fast and clean sync
    - name: 📂 Sync files via Rsync
      run: |
        rsync -avz --delete \
          -e "ssh -p ${{ secrets.SFTP_PORT }} -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:~/domains/skylinecommerce.in/test/
        # The --delete flag ensures that files removed from your repo are also removed from the server.

